=== cschroed-usgs/sparrow-dss/trunk/sparrow-business/src/main/resources/gov/usgswim/sparrow/meta_response.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.usgs.gov/sparrow/meta_response/v0_1"
            targetNamespace="http://www.usgs.gov/sparrow/meta_response/v0_1"
            elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="models">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="model" type="ModelType" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="ModelType">
		<xsd:sequence>
			<xsd:element name="status" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="approved" type="xsd:boolean"/>
						<xsd:element name="public" type="xsd:boolean"/>
						<xsd:element name="archived" type="xsd:boolean"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="url" type="xsd:string" minOccurs="0"/>
			<xsd:element name="dateAdded" type="xsd:date"/>
			<xsd:element name="contactId" type="xsd:integer"/>
			<xsd:element name="enhNetworkId" type="xsd:integer"/>
			<xsd:element name="bounds">
			    <xsd:complexType>
					<xsd:attribute name="north" use="required" type="xsd:decimal"/>
					<xsd:attribute name="west" use="required" type="xsd:decimal"/>
					<xsd:attribute name="south" use="required" type="xsd:decimal"/>
					<xsd:attribute name="east" use="required" type="xsd:decimal"/>
			    </xsd:complexType>
			</xsd:element>
			<xsd:element name="sources">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="source" type="SourceType"
												 maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:decimal" use="required"/>
	</xsd:complexType>
    <xsd:complexType name="SourceType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="displayName" type="xsd:string"/>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="constituent" type="xsd:string"/>
			<xsd:element name="units" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="id" use="required" type="xsd:integer"/>
		<xsd:attribute name="identifier" use="required" type="xsd:integer"/>
		<xsd:attribute name="sortOrder" use="required" type="xsd:integer"/>
    </xsd:complexType>
</xsd:schema>

=== cschroed-usgs/sparrow-dss/src/main/resources/models/modelServiceError.xml
<models xmlns="http://www.usgs.gov/sparrow/meta_response/v0_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.usgs.gov/sparrow/meta_response/v0_1 http://www.usgs.gov/sparrow/meta_response.xsd">
	<model id="-1">
		<status>
			<approved>true</approved>
			<public>true</public>
			<archived>false</archived>
		</status>
		<!-- %s -->
		<name>test</name>
		<alias>test</alias>
		<description>Test Model</description>
		<dateAdded>2009-09-03</dateAdded>
		<contactId>21</contactId>
		<enhNetworkId>1</enhNetworkId>
		<bounds north="41.019231" west="-80.922115" south="36.519231" east="-74.172115"></bounds>
		<sources>
			<source id="30" identifier="1" sortOrder="1"><name>atdep_mean_res</name><displayName>Atm. deposition</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
			<source id="31" identifier="2" sortOrder="2"><name>manfert_n</name><displayName>Fertilizer (manure)</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
		</sources>
	</model>
</models>

=== cschroed-usgs/sparrow-dss/trunk/sparrow-service/src/main/webapp/serviceTests/testResults/model.xml
<models xmlns="http://www.usgs.gov/sparrow/meta_response/v0_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.usgs.gov/sparrow/meta_response/v0_1 http://www.usgs.gov/sparrow/meta_response.xsd"><model id="1"><status><approved>true</approved><public>true</public><archived>false</archived></status><name>Chesapeake bay</name><description>Chesapeake bay Test Model</description><dateAdded>2007-03-22</dateAdded><contactId>21</contactId><enhNetworkId>1</enhNetworkId><bounds north="41.019231" west="-80.922115" south="36.519231" east="-74.172115"></bounds><sources><source id="1" identifier="1" sortOrder="1"><name>pttn</name><displayName>pttn</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="2" identifier="2" sortOrder="2"><name>area</name><displayName>area</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="3" identifier="3" sortOrder="3"><name>frtn</name><displayName>frtn</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="4" identifier="4" sortOrder="4"><name>atmd</name><displayName>atmd</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="5" identifier="5" sortOrder="5"><name>mann</name><displayName>mann</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="6" identifier="6" sortOrder="6"><name>urbn</name><displayName>urbn</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="7" identifier="7" sortOrder="7"><name>septic</name><displayName>septic</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="8" identifier="8" sortOrder="8"><name>crop</name><displayName>crop</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="9" identifier="9" sortOrder="9"><name>past</name><displayName>past</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="10" identifier="10" sortOrder="10"><name>tagr</name><displayName>tagr</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="11" identifier="11" sortOrder="11"><name>frst</name><displayName>frst</displayName><constituent>Unknown</constituent><units>Unknown</units></source>
</sources></model><model id="21"><status><approved>true</approved><public>true</public><archived>false</archived></status><name>Chesapeake bay v2</name><description>Chesapeake bay Test Model</description><dateAdded>2007-05-25</dateAdded><contactId>21</contactId><enhNetworkId>1</enhNetworkId><bounds north="41.019231" west="-80.922115" south="36.519231" east="-74.172115"></bounds><sources><source id="1" identifier="1" sortOrder="1"><name>pttn</name><displayName>pttn</displayName><description>pttn</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="2" identifier="2" sortOrder="2"><name>area</name><displayName>area</displayName><description>area</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="3" identifier="3" sortOrder="3"><name>frtn</name><displayName>frtn</displayName><description>frtn</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="4" identifier="4" sortOrder="4"><name>atmd</name><displayName>atmd</displayName><description>atmd</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="5" identifier="5" sortOrder="5"><name>mann</name><displayName>mann</displayName><description>mann</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="6" identifier="6" sortOrder="6"><name>urbn</name><displayName>urbn</displayName><description>urbn</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="7" identifier="7" sortOrder="7"><name>septic</name><displayName>septic</displayName><description>septic</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="8" identifier="8" sortOrder="8"><name>crop</name><displayName>crop</displayName><description>crop</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="9" identifier="9" sortOrder="9"><name>past</name><displayName>past</displayName><description>past</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="10" identifier="10" sortOrder="10"><name>tagr</name><displayName>tagr</displayName><description>tagr</description><constituent>Unknown</constituent><units>Unknown</units></source>
<source id="11" identifier="11" sortOrder="11"><name>frst</name><displayName>frst</displayName><description>frst</description><constituent>Unknown</constituent><units>Unknown</units></source>
</sources></model><model id="22"><status><approved>true</approved><public>true</public><archived>false</archived></status><name>national Model</name><description>A national model based on the E2RF1 dataset.</description><dateAdded>2007-05-30</dateAdded><contactId>42</contactId><enhNetworkId>22</enhNetworkId><bounds north="53.218919" west="-126.0" south="20.381081" east="-66.0"></bounds><sources><source id="1" identifier="1" sortOrder="1"><name>POINT</name><displayName>POINT</displayName><description>POINT</description><constituent>Total Nitrogen</constituent><units>kg /year</units></source>
<source id="2" identifier="2" sortOrder="2"><name>ATMDEP</name><displayName>ATMDEP</displayName><description>ATMDEP</description><constituent>Total Nitrogen</constituent><units>kg /year</units></source>
<source id="3" identifier="3" sortOrder="3"><name>FERTILIZER</name><displayName>FERTILIZER</displayName><description>FERTILIZER</description><constituent>Total Nitrogen</constituent><units>kg /year</units></source>
<source id="4" identifier="4" sortOrder="4"><name>WASTE</name><displayName>WASTE</displayName><description>WASTE</description><constituent>Total Nitrogen</constituent><units>kg /year</units></source>
<source id="5" identifier="5" sortOrder="5"><name>NONAGR</name><displayName>NONAGR</displayName><description>NONAGR</description><constituent>Area</constituent><units>sqr. km</units></source>
</sources></model></models>
